name: Deploy

on:
  push:
    branches: 
      - main
env:
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_USER: Rajendro1

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Podman image
      run: |
        podman build . --tag ghcr.io/rajendro1/antino-go-$(basename ${{ github.ref }}):$(basename ${{ github.ref }}) -f Dockerfile
        podman push ghcr.io/rajendro1/antino-go-$(basename ${{ github.ref }}):$(basename ${{ github.ref }})